# Generated by Django 4.2.1 on 2023-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentomodel',
            name='agObserv',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='agendamodel',
            name='agQtdTem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo'),
        ),
    ]
