# Generated by Django 4.2.1 on 2023-10-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamentomodel_agobserv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentomodel',
            name='agAgenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agendamento.agendamodel', verbose_name='agenda'),
        ),
    ]
