# Generated by Django 4.2.1 on 2023-10-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_agendamentomodel_agagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamodel',
            name='agQtdTot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
