# Generated by Django 4.2.1 on 2023-10-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamodel_agqtdtot'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentomodel',
            name='agSituac',
            field=models.CharField(choices=[['agendado', 'Agendado'], ['atendido', 'Atendido']], default='agendado', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='agendamentomodel',
            name='agAgenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agendamento.agendamodel', verbose_name='Agenda'),
        ),
    ]
