# Generated by Django 4.2.1 on 2023-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_agendamentomodel_agsituac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentomodel',
            name='agSituac',
            field=models.CharField(blank=True, choices=[['agendado', 'Agendado'], ['atendido', 'Atendido']], default='agendado', max_length=30, verbose_name='Situação'),
        ),
    ]
