# Generated by Django 4.2.1 on 2023-11-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0036_motivosatendimentomodel_atendimentomodel_amotaten'),
        ('agendamento', '0006_alter_agendamentomodel_agsituac'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentomodel',
            name='aMotAten',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='atendimento.motivosatendimentomodel', verbose_name='Motivo de Atendimento'),
        ),
        migrations.AddField(
            model_name='agendamodel',
            name='aMotAten',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='atendimento.motivosatendimentomodel', verbose_name='Motivo de Agendamento'),
        ),
    ]
