# Generated by Django 4.2.1 on 2023-07-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='MarcaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItensInsumoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorUnitario', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('valorTotal', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('insumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.insumomodel', verbose_name='Insumo')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.marcamodel', verbose_name='Marca')),
            ],
        ),
    ]
