# Generated by Django 4.2.1 on 2023-08-17 23:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_clientmodel_profissao'),
        ('estoque', '0002_remove_itensinsumomodel_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoInsumoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('Entrada', 'entrada'), ('Saída', 'Saída')], default='Entrada', max_length=10, verbose_name='Operação')),
                ('data', models.DateField(default=datetime.date.today)),
                ('unidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.localmodel', verbose_name='Unidade')),
            ],
        ),
    ]
