# Generated by Django 4.2.1 on 2023-08-18 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_movimentacaoinsumomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensinsumomodel',
            name='movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.movimentacaoinsumomodel'),
        ),
        migrations.AlterField(
            model_name='movimentacaoinsumomodel',
            name='operacao',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], default='Entrada', max_length=10, verbose_name='Operação'),
        ),
    ]
