# Generated by Django 4.2.1 on 2023-08-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_itensinsumomodel_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumomodel',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
