# Generated by Django 4.2.1 on 2023-08-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_alter_insumomodel_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumomodel',
            name='valor',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Valor'),
        ),
    ]
