# Generated by Django 4.2.1 on 2023-09-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_itensinsumomodel_valortotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='quantidade',
            field=models.IntegerField(null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='serie',
            field=models.CharField(max_length=20, null=True, verbose_name='Serie/Lote'),
        ),
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='valorUnitario',
            field=models.CharField(max_length=10, null=True, verbose_name='Valor Unitario'),
        ),
    ]
