# Generated by Django 4.2.1 on 2023-09-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_alter_itensinsumomodel_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='movimentacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.movimentacaoinsumomodel'),
        ),
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='valorTotal',
            field=models.CharField(max_length=10, null=True, verbose_name='Valor Total'),
        ),
    ]
