# Generated by Django 4.2.1 on 2023-09-20 12:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_itensmovimentacaoinsumomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensmovimentacaoinsumomodel',
            name='movimentacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.movimentacaoinsumomodel', verbose_name='Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacaoinsumomodel',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
    ]
