# Generated by Django 4.2.1 on 2023-09-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_alter_itensmovimentacaoinsumomodel_movimentacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoInsumoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('perfis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Perfis')),
                ('controleDeCompra', models.BooleanField(default=False, verbose_name='Controle de Compra')),
            ],
        ),
    ]
