# Generated by Django 4.2.1 on 2023-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_grupoinsumomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoinsumomodel',
            name='controleDeCompra',
            field=models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim')], default=1, max_length=3, verbose_name='Controle de Compra'),
        ),
    ]
