# Generated by Django 4.2.1 on 2023-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_itensmovimentacaoinsumomodel_valorcompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumomodel',
            name='quantidade',
            field=models.CharField(blank=True, default=0, max_length=15, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='insumomodel',
            name='valor',
            field=models.CharField(blank=True, default=0.0, max_length=15, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='itensmovimentacaoinsumomodel',
            name='valorCompra',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Valor Compra'),
        ),
    ]
