# Generated by Django 4.2.1 on 2023-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0021_alter_insumomodel_quantidade_alter_insumomodel_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoinsumomodel',
            name='tipoMovimentacao',
            field=models.CharField(choices=[('usoProprio', 'Uso próprio'), ('compra', 'Compra'), ('venda', 'Venda'), ('doacao', 'Doação')], default=2, max_length=20, verbose_name='Tipo de Movimentação'),
        ),
    ]
