# Generated by Django 4.2.1 on 2023-09-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_movimentacaoinsumomodel_tipomovimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumomodel',
            name='quantidadeMin',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Estoque Mínimo'),
        ),
    ]
