# Generated by Django 4.2.1 on 2023-09-22 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_clientmodel_born_alter_clientmodel_last_name_and_more'),
        ('estoque', '0023_insumomodel_quantidademin'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoinsumomodel',
            name='eClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.clientmodel', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='marcamodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
    ]
