# Generated by Django 4.2.1 on 2023-10-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_movimentacaoinsumomodel_eclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumomodel',
            name='controle',
            field=models.CharField(choices=[('lote', 'Lote'), ('quantidade', 'Quantidade')], default='lote', max_length=10, verbose_name='Tipo de Controle'),
        ),
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie/Lote'),
        ),
        migrations.AlterField(
            model_name='itensmovimentacaoinsumomodel',
            name='serie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie/Lote'),
        ),
    ]
