# Generated by Django 4.2.1 on 2023-11-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_movimentacaoinsumomodel_observacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacaoinsumomodel',
            old_name='observacoes',
            new_name='observacao',
        ),
    ]
