# Generated by Django 4.2.1 on 2023-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0027_rename_observacoes_movimentacaoinsumomodel_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='valorTotal',
            field=models.CharField(max_length=15, null=True, verbose_name='Val. Total'),
        ),
        migrations.AlterField(
            model_name='itensinsumomodel',
            name='valorUnitario',
            field=models.CharField(max_length=15, null=True, verbose_name='Val. Unitario'),
        ),
        migrations.AlterField(
            model_name='itensmovimentacaoinsumomodel',
            name='valorCompra',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Val. Compra'),
        ),
        migrations.AlterField(
            model_name='itensmovimentacaoinsumomodel',
            name='valorTotal',
            field=models.CharField(max_length=15, null=True, verbose_name='Val. Total'),
        ),
        migrations.AlterField(
            model_name='itensmovimentacaoinsumomodel',
            name='valorUnitario',
            field=models.CharField(max_length=15, null=True, verbose_name='Val. Unitario'),
        ),
    ]
