# Generated by Django 5.0.1 on 2024-03-17 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0028_alter_itensinsumomodel_valortotal_and_more'),
        ('home', '0038_alter_clientmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoinsumomodel',
            name='eClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.clientmodel', verbose_name='Cliente'),
        ),
    ]
