# Generated by Django 4.2.1 on 2023-05-28 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('born', models.DateField()),
                ('street', models.CharField(blank=True, max_length=30, verbose_name='Logradouro')),
                ('district', models.CharField(blank=True, max_length=30, verbose_name='Bairro')),
                ('number', models.IntegerField(blank=True, verbose_name='Número')),
                ('zipcode', models.IntegerField(blank=True, verbose_name='CEP')),
                ('document1', models.IntegerField(blank=True, verbose_name='CPF')),
                ('document2', models.IntegerField(blank=True, verbose_name='RG')),
                ('telefone1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefone')),
                ('telefone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Celular')),
                ('status', models.BooleanField(default=True)),
                ('responsibleName', models.CharField(blank=True, max_length=50, verbose_name='Responsável')),
                ('responsiblePhone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Contato')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.citymodel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
