# Generated by Django 4.2.1 on 2023-05-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='telefone1',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='telefone2',
            new_name='phone2',
        ),
    ]
