# Generated by Django 4.2.1 on 2023-05-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_statusmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='born',
            field=models.DateTimeField(verbose_name='Data de Nascimento'),
        ),
    ]
