# Generated by Django 4.2.1 on 2023-05-28 22:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_clientmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='document1',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='document2',
            field=models.IntegerField(blank=True, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='responsibleName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='responsiblePhone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='street',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Logradouro'),
        ),
    ]
