# Generated by Django 4.2.1 on 2023-05-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_clientmodel_status_alter_statusmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.statusmodel', verbose_name='Situação'),
        ),
    ]
