# Generated by Django 4.2.1 on 2023-05-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_clientmodel_owner_alter_clientmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='CEP'),
        ),
    ]
