# Generated by Django 4.2.1 on 2023-05-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_clientmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='owner',
        ),
    ]
