# Generated by Django 4.2.1 on 2023-06-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_clientmodel_city_alter_clientmodel_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityModel',
        ),
        migrations.DeleteModel(
            name='StateModel',
        ),
    ]
