# Generated by Django 4.2.1 on 2023-06-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_specialtymodel_professionalmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalmodel',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.specialtymodel', verbose_name='Especialidade'),
        ),
    ]
