# Generated by Django 4.2.1 on 2023-06-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_professionalmodel_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='profissao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Profissão'),
        ),
    ]
