# Generated by Django 4.2.1 on 2023-08-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_clientmodel_profissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='document1',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
