# Generated by Django 4.2.1 on 2023-08-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_clientmodel_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='document2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='RG'),
        ),
    ]
