# Generated by Django 4.2.1 on 2023-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_clientmodel_document2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='responsiblePhone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato'),
        ),
    ]
