# Generated by Django 4.2.1 on 2023-09-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_clientmodel_phone1_alter_clientmodel_phone2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.statusmodel', verbose_name='Situação'),
        ),
    ]
