# Generated by Django 4.2.1 on 2023-09-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_profissao_clientmodel_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='born',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='typeRegister',
            field=models.CharField(choices=[('simplificado', 'Simplificado'), ('completo', 'Completo')], default=1, max_length=15, verbose_name='Tipo do Cadastro'),
        ),
    ]
