# Generated by Django 4.2.1 on 2023-09-25 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_clientmodel_born_alter_clientmodel_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localmodel',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.statusmodel', verbose_name='Situação'),
        ),
    ]
