# Generated by Django 4.2.1 on 2023-11-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_localmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.statusmodel', verbose_name='Situação'),
        ),
    ]
