# Generated by Django 5.0.1 on 2024-03-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_clientmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='zipcode',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
