# Generated by Django 5.0.1 on 2024-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_clientmodel_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='document1',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='document2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RG'),
        ),
    ]
