# Generated by Django 4.2.1 on 2023-06-29 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_clientmodel_profissao'),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='conheceu',
            new_name='aApaIndi',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='client',
            new_name='aClient',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question1',
            new_name='aConhece',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='data',
            new_name='aDataOOO',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question2',
            new_name='aDifiEsc',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question3',
            new_name='aDifiPio',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question4',
            new_name='aFormPag',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question6a',
            new_name='aJaTesAp',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question6b',
            new_name='aJaUsoAp',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question5',
            new_name='aMarcaOO',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question6j',
            new_name='aOutrDif',
        ),
        migrations.RenameField(
            model_name='atendimentomodel',
            old_name='question7h',
            new_name='aOutrDoe',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question6c',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question6d',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question6e',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question6f',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question6g',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question6h',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question6i',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question7a',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question7b',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question7c',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question7d',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question7e',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question7f',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='question7g',
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aCancerO',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aCardiop',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aCineTea',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aCiruOuv',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aCoceira',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aColeAlt',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aConvGru',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aConvRui',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aDiabete',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aDorOOOO',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aFalaBai',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aFaladis',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aLabirin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aLadoInd',
            field=models.CharField(blank=True, choices=[('OE', 'Ouvido Esquerdo'), ('OD', 'Ouvido Direito'), ('Ambos', 'Ambos')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aLocal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.localmodel', verbose_name='Unidade de Atendimento'),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aOtiteOO',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aOutrOuv',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aOuviMel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aPaleSal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aPessFam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aPresAlt',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aProbRin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aProbTir',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aProfessional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.professionalmodel', verbose_name='Profissional'),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aQualApa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aRetTest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aSaiTest',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aSensTam',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aSituaca',
            field=models.CharField(blank=True, choices=[('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aTeleCel',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aTeleFix',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aTelevis',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aTempoOO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aTimpPer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aTontura',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aTrabRui',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aUsoOtot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aValApar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aZumbido',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
