# Generated by Django 4.2.1 on 2023-07-02 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0006_anamnesemodel_remove_atendimentomodel_adataooo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='aDataAna',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
