# Generated by Django 4.2.1 on 2023-07-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0007_alter_anamnesemodel_adataana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnesemodel',
            old_name='aObserva',
            new_name='aAObserv',
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='aInfoTec',
        ),
    ]
