# Generated by Django 4.2.1 on 2023-07-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0018_alter_anamnesemodel_aidatend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentomodel',
            name='aSituaca',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído')], default='Em Andamento', max_length=15),
        ),
    ]
