# Generated by Django 4.2.1 on 2023-07-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0020_alter_anamnesemodel_aidatend'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnesemodel',
            name='atendimentoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.atendimentomodel'),
        ),
        migrations.AlterField(
            model_name='anamnesemodel',
            name='aIDAtend',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
