# Generated by Django 4.2.1 on 2023-07-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0021_anamnesemodel_atendimentoid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesemodel',
            name='atendimentoid',
        ),
    ]
