# Generated by Django 4.2.1 on 2023-07-15 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0022_remove_anamnesemodel_atendimentoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='aIDAtend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.atendimentomodel'),
        ),
    ]
