# Generated by Django 4.2.1 on 2023-09-15 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0023_alter_anamnesemodel_aidatend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesemodel',
            name='aDataAna',
            field=models.CharField(default=datetime.date.today, max_length=10),
        ),
        migrations.AlterField(
            model_name='atendimentomodel',
            name='aDataPri',
            field=models.CharField(max_length=10, null=True, verbose_name='Data 1ª consulta'),
        ),
    ]
