# Generated by Django 4.2.1 on 2023-09-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0025_alter_anamnesemodel_adataana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatosTelefonicosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aDemanda', models.CharField(blank=True, choices=[('telefone', 'Telefone'), ('espontanea', 'Espontânea'), ('agendamento', 'Agendamento')], default=2, max_length=15, null=True, verbose_name='Demanda')),
                ('aTelData', models.DateField(verbose_name='Data Tel.')),
                ('aTelLiga', models.CharField(max_length=20, verbose_name='Telefone')),
                ('aTelObse', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aDemanda',
            field=models.CharField(blank=True, choices=[('telefone', 'Telefone'), ('espontanea', 'Espontânea'), ('agendamento', 'Agendamento')], default=2, max_length=15, null=True, verbose_name='Demanda'),
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aObsAten',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
