# Generated by Django 4.2.1 on 2023-09-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0027_contatostelefonicosmodel_aidatend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatostelefonicosmodel',
            name='aTelData',
            field=models.DateField(verbose_name='Data Telefonema'),
        ),
    ]
