# Generated by Django 4.2.1 on 2023-09-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0029_audiometriamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiometriamodel',
            old_name='aLocal',
            new_name='auLocal',
        ),
        migrations.RenameField(
            model_name='audiometriamodel',
            old_name='aProfessional',
            new_name='auProfessional',
        ),
    ]
