# Generated by Django 4.2.1 on 2023-10-05 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0030_rename_alocal_audiometriamodel_aulocal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiometriamodel',
            name='auCalib',
            field=models.DateField(blank=True, null=True, verbose_name='Calibração'),
        ),
        migrations.AlterField(
            model_name='audiometriamodel',
            name='auData',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='audiometriamodel',
            name='auObser',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
