# Generated by Django 4.2.1 on 2023-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0031_alter_audiometriamodel_aucalib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentomodel',
            name='aAgendam',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
