# Generated by Django 4.2.1 on 2023-10-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0032_atendimentomodel_aagendam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='aAgendam',
        ),
    ]
