# Generated by Django 4.2.1 on 2023-10-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0033_remove_atendimentomodel_aagendam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatostelefonicosmodel',
            name='aTelData',
            field=models.DateField(blank=True, null=True, verbose_name='Data Telefonema'),
        ),
        migrations.AlterField(
            model_name='contatostelefonicosmodel',
            name='aTelLiga',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
