# Generated by Django 4.2.1 on 2023-11-07 23:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0034_alter_contatostelefonicosmodel_ateldata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulagemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aAjustOD', models.CharField(blank=True, max_length=50, null=True)),
                ('aAjustOE', models.CharField(blank=True, max_length=50, null=True)),
                ('aAObserv', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='atendimentomodel',
            name='aSituaca',
        ),
        migrations.RemoveField(
            model_name='contatostelefonicosmodel',
            name='aDemanda',
        ),
        migrations.RemoveField(
            model_name='contatostelefonicosmodel',
            name='aTelData',
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aDataAte',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='atendimentomodel',
            name='aDataPri',
            field=models.DateField(blank=True, null=True, verbose_name='Data 1ª consulta'),
        ),
        migrations.DeleteModel(
            name='AnamneseModel',
        ),
        migrations.AddField(
            model_name='regulagemmodel',
            name='aIDAtend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.atendimentomodel'),
        ),
    ]
