# Generated by Django 4.2.1 on 2023-11-09 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0035_regulagemmodel_remove_atendimentomodel_asituaca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosAtendimentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='atendimentomodel',
            name='aMotAten',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='atendimento.motivosatendimentomodel', verbose_name='Motivo de Atendimento'),
        ),
    ]
