# Generated by Django 4.2.1 on 2023-11-09 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0036_motivosatendimentomodel_atendimentomodel_amotaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentomodel',
            name='aMotAten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.motivosatendimentomodel', verbose_name='Motivo de Atendimento'),
        ),
    ]
