# Generated by Django 4.2.1 on 2023-11-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0037_alter_atendimentomodel_amotaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatostelefonicosmodel',
            name='aIDAtend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.atendimentomodel'),
        ),
    ]
