# Generated by Django 4.2.1 on 2023-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0038_alter_contatostelefonicosmodel_aidatend'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiometriamodel',
            name='auCoordenadas_planoII_Linha1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audiometriamodel',
            name='auCoordenadas_planoII_Linha2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audiometriamodel',
            name='auCoordenadas_planoI_Linha1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audiometriamodel',
            name='auCoordenadas_planoI_Linha2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
